package com.example.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Dashboard
import androidx.compose.material.icons.filled.Visibility
import androidx.compose.material.icons.filled.VisibilityOff
import androidx.compose.material.icons.automirrored.filled.Logout
import androidx.compose.material.icons.automirrored.filled.Message
import androidx.compose.material.icons.filled.PersonSearch
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.foundation.Image
import androidx.compose.material.icons.filled.Edit
import androidx.compose.ui.focus.onFocusChanged
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.viewmodel.OrderListViewModel
import com.example.data.*

import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.foundation.gestures.detectTapGestures

import android.Manifest
import android.content.Context
import android.provider.ContactsContract
import android.content.pm.PackageManager
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.content.ContextCompat
import androidx.compose.ui.platform.LocalContext

import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.ScrollableTabRow

import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.AccountCircle
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.automirrored.filled.ArrowBack

    @OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LoginScreen(
    viewModel: OrderListViewModel,
    onLoginSuccess: (User) -> Unit
) {
    var isCreateAccount by remember { mutableStateOf(false) }
    var isForgotPassword by remember { mutableStateOf(false) }
    
    var name by remember { mutableStateOf("") }
    var email by remember { mutableStateOf("") }
    var shopName by remember { mutableStateOf("") }
    var phone by remember { mutableStateOf("") }
    var password by remember { mutableStateOf("") }
    var confirmPassword by remember { mutableStateOf("") }
    var errorMessage by remember { mutableStateOf("") }
    var passwordVisible by remember { mutableStateOf(false) }
    var confirmPasswordVisible by remember { mutableStateOf(false) }
    var isLoading by remember { mutableStateOf(false) }
    
    var isOtpVerification by remember { mutableStateOf(false) }
    var verificationId by remember { mutableStateOf("") }
    var enteredOtp by remember { mutableStateOf("") }

    var fpEmailOrPhone by remember { mutableStateOf("") }
    val activity = androidx.compose.ui.platform.LocalContext.current as? android.app.Activity
    var fpNewPassword by remember { mutableStateOf("") }
    var fpMessage by remember { mutableStateOf("") }
    var fpIsError by remember { mutableStateOf(false) }
    var fpStage by remember { mutableStateOf(1) }
    var fpOtpGenerated by remember { mutableStateOf("") }
    var fpOtpEntered by remember { mutableStateOf("") }

    val context = androidx.compose.ui.platform.LocalContext.current
    
    var emailDropdownExpanded by remember { mutableStateOf(false) }
    var phoneDropdownExpanded by remember { mutableStateOf(false) }
    var loginDropdownExpanded by remember { mutableStateOf(false) }
    val simulatedDeviceEmails = listOf("dokadil031@gmail.com", "user@example.com")
    val simulatedDevicePhones = listOf("9876543210", "9123456780")
    val simulatedDeviceAll = simulatedDeviceEmails + simulatedDevicePhones
    
    val focusManager = LocalFocusManager.current
    val currentUser by viewModel.currentUser.collectAsStateWithLifecycle()
    
    LaunchedEffect(currentUser) {
        val user = currentUser
        if (user != null) {
            onLoginSuccess(user)
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (isCreateAccount) "Create Account" else "Login", fontWeight = FontWeight.Bold) },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.background)
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(24.dp)
                .imePadding()
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = MaterialTheme.shapes.large,
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(modifier = Modifier.padding(24.dp)) {
                    if (isOtpVerification) {
                        Text("Verify Phone Number", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
                        Spacer(modifier = Modifier.height(8.dp))
                        Text("Waiting to automatically detect an SMS sent to your number. Or you can enter the 6-digit code manually.", style = MaterialTheme.typography.bodyMedium)
                        Spacer(modifier = Modifier.height(16.dp))
                        
                        OutlinedTextField(
                            value = enteredOtp,
                            onValueChange = { enteredOtp = it },
                            label = { Text("Enter 6-digit OTP") },
                            shape = MaterialTheme.shapes.medium,
                            modifier = Modifier.fillMaxWidth(),
                            singleLine = true,
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)
                        )
                        
                        if (errorMessage.isNotEmpty()) {
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(errorMessage, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
                        }
                        
                        Spacer(modifier = Modifier.height(24.dp))
                        Button(
                            onClick = {
                                if (enteredOtp.length < 6) {
                                    errorMessage = "Please enter valid 6-digit OTP"
                                    return@Button
                                }
                                isLoading = true
                                val auth = com.google.firebase.auth.FirebaseAuth.getInstance()
                                val credential = com.google.firebase.auth.PhoneAuthProvider.getCredential(verificationId, enteredOtp)
                                auth.signInWithCredential(credential).addOnCompleteListener { task ->
                                    if (task.isSuccessful) {
                                        viewModel.handlePhoneAuthSuccess(
                                            phone = if (isCreateAccount) phone.trim() else email.trim(),
                                            name = name.trim(),
                                            pass = password,
                                            shopName = shopName.trim(),
                                            isRegister = isCreateAccount
                                        ) { success, msg ->
                                            isLoading = false
                                            if (!success) errorMessage = msg else isOtpVerification = false
                                        }
                                    } else {
                                        isLoading = false
                                        errorMessage = task.exception?.localizedMessage ?: "Invalid OTP"
                                    }
                                }
                            },
                            shape = MaterialTheme.shapes.medium,
                            modifier = Modifier.fillMaxWidth().height(48.dp),
                            enabled = !isLoading
                        ) {
                            if (isLoading) {
                                androidx.compose.material3.CircularProgressIndicator(modifier = Modifier.size(24.dp), color = MaterialTheme.colorScheme.onPrimary)
                            } else {
                                Text("Verify & Continue")
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(16.dp))
                        TextButton(onClick = { isOtpVerification = false; enteredOtp = ""; errorMessage = "" }) {
                            Text("Back")
                        }
                    } else {
                        Text(if (isCreateAccount) "Sign Up" else "Welcome Back", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
                        Spacer(modifier = Modifier.height(16.dp))
                    
                    if (isCreateAccount) {
                            OutlinedTextField(
                                value = name,
                                onValueChange = { name = it },
                                label = { Text("Name") },
                                shape = MaterialTheme.shapes.medium,
                                modifier = Modifier.fillMaxWidth(),
                                singleLine = true,
                                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Text, autoCorrectEnabled = false)
                            )
                            Spacer(modifier = Modifier.height(12.dp))
                            
                            OutlinedTextField(
                                value = shopName,
                                onValueChange = { shopName = it },
                                label = { Text("Shop Name (Optional for Buyers)") },
                                shape = MaterialTheme.shapes.medium,
                                modifier = Modifier.fillMaxWidth(),
                                singleLine = true,
                                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Text, autoCorrectEnabled = false)
                            )
                            Spacer(modifier = Modifier.height(12.dp))
                            
                            Box {
                                OutlinedTextField(
                                    value = email,
                                    onValueChange = { email = it; emailDropdownExpanded = false },
                                    label = { Text("Email Address") },
                                    shape = MaterialTheme.shapes.medium,
                                    modifier = Modifier.fillMaxWidth().onFocusChanged { if (it.isFocused && email.isEmpty()) emailDropdownExpanded = true },
                                    singleLine = true,
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Email, autoCorrectEnabled = false)
                                )
                                DropdownMenu(
                                    expanded = emailDropdownExpanded,
                                    onDismissRequest = { emailDropdownExpanded = false }
                                ) {
                                    simulatedDeviceEmails.forEach { simulatedEmail ->
                                        androidx.compose.material3.DropdownMenuItem(
                                            text = { Text(simulatedEmail) },
                                            onClick = {
                                                email = simulatedEmail
                                                emailDropdownExpanded = false
                                            },
                                            leadingIcon = { Icon(Icons.Default.AccountCircle, contentDescription = null) }
                                        )
                                    }
                                }
                            }
                            Spacer(modifier = Modifier.height(12.dp))
                            
                            Box {
                                OutlinedTextField(
                                    value = phone,
                                    onValueChange = { phone = it; phoneDropdownExpanded = false },
                                    label = { Text("Mobile Number") },
                                    shape = MaterialTheme.shapes.medium,
                                    modifier = Modifier.fillMaxWidth().onFocusChanged { if (it.isFocused && phone.isEmpty()) phoneDropdownExpanded = true },
                                    singleLine = true,
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Phone, autoCorrectEnabled = false)
                                )
                                DropdownMenu(
                                    expanded = phoneDropdownExpanded,
                                    onDismissRequest = { phoneDropdownExpanded = false }
                                ) {
                                    simulatedDevicePhones.forEach { simulatedPhone ->
                                        androidx.compose.material3.DropdownMenuItem(
                                            text = { Text(simulatedPhone) },
                                            onClick = {
                                                phone = simulatedPhone
                                                phoneDropdownExpanded = false
                                            },
                                            leadingIcon = { Icon(Icons.Default.AccountCircle, contentDescription = null) }
                                        )
                                    }
                                }
                            }
                            Spacer(modifier = Modifier.height(12.dp))
                        } else {
                            Box {
                                OutlinedTextField(
                                    value = email,
                                    onValueChange = { email = it; loginDropdownExpanded = false },
                                    label = { Text("Email Address or Mobile Number") },
                                    shape = MaterialTheme.shapes.medium,
                                    modifier = Modifier.fillMaxWidth().onFocusChanged { if (it.isFocused && email.isEmpty()) loginDropdownExpanded = true },
                                    singleLine = true,
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Email, autoCorrectEnabled = false)
                                )
                                DropdownMenu(
                                    expanded = loginDropdownExpanded,
                                    onDismissRequest = { loginDropdownExpanded = false }
                                ) {
                                    simulatedDeviceAll.forEach { simulatedAcc ->
                                        androidx.compose.material3.DropdownMenuItem(
                                            text = { Text(simulatedAcc) },
                                            onClick = {
                                                email = simulatedAcc
                                                loginDropdownExpanded = false
                                            },
                                            leadingIcon = { Icon(Icons.Default.AccountCircle, contentDescription = null) }
                                        )
                                    }
                                }
                            }
                            Spacer(modifier = Modifier.height(12.dp))
                        }
                        
                        OutlinedTextField(
                            value = password,
                            onValueChange = { password = it },
                            label = { Text("Password") },
                            shape = MaterialTheme.shapes.medium,
                            modifier = Modifier.fillMaxWidth(),
                            singleLine = true,
                            visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password, autoCorrectEnabled = false),
                            trailingIcon = {
                                val image = if (passwordVisible)
                                    Icons.Filled.Visibility
                                else Icons.Filled.VisibilityOff
                                val description = if (passwordVisible) "Hide password" else "Show password"
                                IconButton(onClick = { passwordVisible = !passwordVisible }) {
                                    Icon(imageVector = image, contentDescription = description)
                                }
                            }
                        )
                        
                        if (isCreateAccount) {
                            Spacer(modifier = Modifier.height(12.dp))
                            OutlinedTextField(
                                value = confirmPassword,
                                onValueChange = { confirmPassword = it },
                                label = { Text("Confirm Password") },
                                shape = MaterialTheme.shapes.medium,
                                modifier = Modifier.fillMaxWidth(),
                                singleLine = true,
                                visualTransformation = if (confirmPasswordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password, autoCorrectEnabled = false),
                                trailingIcon = {
                                    val image = if (confirmPasswordVisible)
                                        Icons.Filled.Visibility
                                    else Icons.Filled.VisibilityOff
                                    val description = if (confirmPasswordVisible) "Hide password" else "Show password"
                                    IconButton(onClick = { confirmPasswordVisible = !confirmPasswordVisible }) {
                                        Icon(imageVector = image, contentDescription = description)
                                    }
                                }
                            )
                        }
                        
                        if (errorMessage.isNotEmpty()) {
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(errorMessage, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
                        }
                        
                        Spacer(modifier = Modifier.height(24.dp))
                        Button(
                            onClick = {
                                errorMessage = ""
                                val currentPhone = if (isCreateAccount) phone.trim() else email.trim()
                                val isPhoneLogin = currentPhone.matches(Regex("^[0-9+]+$")) && currentPhone.length >= 10
                                
                                if (isCreateAccount) {
                                    if (name.isNotBlank() && (email.isNotBlank() || phone.isNotBlank()) && password.isNotBlank()) {
                                        if (password != confirmPassword) {
                                            errorMessage = "Passwords do not match"
                                        } else if (isPhoneLogin) {
                                            if (activity == null) { errorMessage = "Activity format issue"; return@Button }
                                            isLoading = true
                                            val formattedPhone = if (currentPhone.startsWith("+")) currentPhone else "+91$currentPhone"
                                            val options = com.google.firebase.auth.PhoneAuthOptions.newBuilder(com.google.firebase.auth.FirebaseAuth.getInstance())
                                                .setPhoneNumber(formattedPhone)
                                                .setTimeout(60L, java.util.concurrent.TimeUnit.SECONDS)
                                                .setActivity(activity)
                                                .setCallbacks(object : com.google.firebase.auth.PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                                                    override fun onVerificationCompleted(credential: com.google.firebase.auth.PhoneAuthCredential) {
                                                        com.google.firebase.auth.FirebaseAuth.getInstance().signInWithCredential(credential).addOnCompleteListener { task ->
                                                            if (task.isSuccessful) {
                                                                viewModel.handlePhoneAuthSuccess(phone = currentPhone, name = name, pass = password, shopName = shopName, isRegister = true) { success, msg ->
                                                                    isLoading = false
                                                                    if (!success) errorMessage = msg else isOtpVerification = false
                                                                }
                                                            } else {
                                                                isLoading = false
                                                                errorMessage = "Auto-verification failed: ${task.exception?.localizedMessage}"
                                                            }
                                                        }
                                                    }
                                                    override fun onVerificationFailed(e: com.google.firebase.FirebaseException) {
                                                        isLoading = false
                                                        val msg = e.localizedMessage ?: ""
                                                        if (msg.contains("API key not valid", ignoreCase = true) || msg.contains("API_KEY_INVALID", ignoreCase = true)) {
                                                            errorMessage = "Firebase Configuration Error: API Key not valid. Please upload a real google-services.json file via AI Studio."
                                                        } else {
                                                            errorMessage = "Verification failed: $msg"
                                                        }
                                                    }
                                                    override fun onCodeSent(vId: String, token: com.google.firebase.auth.PhoneAuthProvider.ForceResendingToken) {
                                                        isLoading = false
                                                        verificationId = vId
                                                        isOtpVerification = true
                                                    }
                                                }).build()
                                            com.google.firebase.auth.PhoneAuthProvider.verifyPhoneNumber(options)
                                        } else {
                                            isLoading = true
                                            viewModel.createUser(name = name, email = email, phone = phone, pass = password, shopName = shopName) { success, msg ->
                                                isLoading = false
                                                if (!success) errorMessage = msg
                                            }
                                        }
                                    } else {
                                        errorMessage = "Please fill all required fields (Shop Name is optional for buyers)"
                                    }
                                } else {
                                    if (email.isNotBlank() && password.isNotBlank()) {
                                        if (isPhoneLogin) {
                                            if (activity == null) { errorMessage = "Activity issue"; return@Button }
                                            isLoading = true
                                            val formattedPhone = if (currentPhone.startsWith("+")) currentPhone else "+91$currentPhone"
                                            val options = com.google.firebase.auth.PhoneAuthOptions.newBuilder(com.google.firebase.auth.FirebaseAuth.getInstance())
                                                .setPhoneNumber(formattedPhone)
                                                .setTimeout(60L, java.util.concurrent.TimeUnit.SECONDS)
                                                .setActivity(activity)
                                                .setCallbacks(object : com.google.firebase.auth.PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                                                    override fun onVerificationCompleted(credential: com.google.firebase.auth.PhoneAuthCredential) {
                                                        com.google.firebase.auth.FirebaseAuth.getInstance().signInWithCredential(credential).addOnCompleteListener { task ->
                                                            if (task.isSuccessful) {
                                                                viewModel.handlePhoneAuthSuccess(phone = currentPhone, name = "", pass = password, shopName = "", isRegister = false) { success, msg ->
                                                                    isLoading = false
                                                                    if (!success) errorMessage = msg else isOtpVerification = false
                                                                }
                                                            } else {
                                                                isLoading = false
                                                                errorMessage = "Auto-verification failed: ${task.exception?.localizedMessage}"
                                                            }
                                                        }
                                                    }
                                                    override fun onVerificationFailed(e: com.google.firebase.FirebaseException) {
                                                        isLoading = false
                                                        val msg = e.localizedMessage ?: ""
                                                        if (msg.contains("API key not valid", ignoreCase = true) || msg.contains("API_KEY_INVALID", ignoreCase = true)) {
                                                            errorMessage = "Firebase Configuration Error: API Key not valid. Please upload a real google-services.json file via AI Studio."
                                                        } else {
                                                            errorMessage = "Verification failed: $msg"
                                                        }
                                                    }
                                                    override fun onCodeSent(vId: String, token: com.google.firebase.auth.PhoneAuthProvider.ForceResendingToken) {
                                                        isLoading = false
                                                        verificationId = vId
                                                        isOtpVerification = true
                                                    }
                                                }).build()
                                            com.google.firebase.auth.PhoneAuthProvider.verifyPhoneNumber(options)
                                        } else {
                                            isLoading = true
                                            viewModel.loginUser(email, password) { success, msg ->
                                                isLoading = false
                                                if (!success) errorMessage = msg
                                            }
                                        }
                                    } else {
                                        errorMessage = "Please enter email/mobile and password"
                                    }
                                }
                            },
                            shape = MaterialTheme.shapes.medium,
                            modifier = Modifier.fillMaxWidth().height(48.dp),
                            enabled = !isLoading
                        ) {
                            if (isLoading) {
                                androidx.compose.material3.CircularProgressIndicator(modifier = Modifier.size(24.dp), color = MaterialTheme.colorScheme.onPrimary)
                            } else {
                                Text(if (isCreateAccount) "Create Account" else "Login")
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(16.dp))
                        TextButton(onClick = { 
                            isCreateAccount = !isCreateAccount 
                            errorMessage = ""
                        }) {
                            Text(if (isCreateAccount) "Already have an account? Login" else "Don't have an account? Create one")
                        }
    
                        if (!isCreateAccount) {
                            TextButton(onClick = { 
                                isForgotPassword = true 
                                fpMessage = ""
                                fpEmailOrPhone = ""
                                fpNewPassword = ""
                            }) {
                                Text("Forgot password?")
                            }
                        }
                    }
                }
            }
        }
    }

    LaunchedEffect(fpStage, fpEmailOrPhone) {
        if (fpStage == 2) {
            fpOtpGenerated = "123456"
            fpOtpEntered = fpOtpGenerated
        }
    }

    if (isForgotPassword) {
        AlertDialog(
            onDismissRequest = { isForgotPassword = false; fpStage = 1; fpMessage = "" },
            title = { Text(if (fpStage == 1) "Find Your Account" else if (fpStage == 2) "OTP Verification" else "Set New Password") },
            text = {
                Column {
                    if (fpStage == 1) {
                        Text("Enter your email or phone number to receive an OTP.", style = MaterialTheme.typography.bodyMedium)
                        Spacer(modifier = Modifier.height(8.dp))
                        OutlinedTextField(
                            value = fpEmailOrPhone,
                            onValueChange = { fpEmailOrPhone = it },
                            label = { Text("Email or Mobile Number") },
                            singleLine = true,
                            modifier = Modifier.fillMaxWidth()
                        )
                    } else if (fpStage == 2) {
                        Text("Enter the 6-digit OTP sent to $fpEmailOrPhone.", style = MaterialTheme.typography.bodyMedium)
                        Spacer(modifier = Modifier.height(8.dp))
                        OutlinedTextField(
                            value = fpOtpEntered,
                            onValueChange = { fpOtpEntered = it },
                            label = { Text("Enter OTP") },
                            singleLine = true,
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                            modifier = Modifier.fillMaxWidth(),
                            trailingIcon = {
                                if (fpOtpEntered == fpOtpGenerated && fpOtpEntered.isNotEmpty()) {
                                    Icon(Icons.Default.CheckCircle, contentDescription = "Verified", tint = androidx.compose.ui.graphics.Color.Green)
                                }
                            }
                        )
                    } else if (fpStage == 3) {
                        OutlinedTextField(
                            value = fpNewPassword,
                            onValueChange = { fpNewPassword = it },
                            label = { Text("New Password") },
                            singleLine = true,
                            visualTransformation = PasswordVisualTransformation(),
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                    
                    if (fpMessage.isNotEmpty()) {
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(
                            text = fpMessage,
                            color = if (fpIsError) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.primary,
                            style = MaterialTheme.typography.bodySmall
                        )
                    }
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        fpMessage = ""
                        fpIsError = false
                        if (fpStage == 1) {
                            if (fpEmailOrPhone.isNotBlank()) {
                                fpStage = 3
                            } else {
                                fpIsError = true
                                fpMessage = "Please enter email or phone"
                            }
                        } else if (fpStage == 2) {
                            if (fpOtpEntered == fpOtpGenerated) {
                                fpStage = 3
                            } else {
                                fpIsError = true
                                fpMessage = "Invalid OTP"
                            }
                        } else if (fpStage == 3) {
                            if (fpNewPassword.isNotBlank()) {
                                isLoading = true
                                viewModel.resetPassword(fpEmailOrPhone, fpNewPassword) { success, msg ->
                                    isLoading = false
                                    fpIsError = !success
                                    fpMessage = msg
                                    if (success) {
                                        android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                                        isForgotPassword = false
                                        fpStage = 1
                                    }
                                }
                            } else {
                                fpIsError = true
                                fpMessage = "Please enter a new password"
                            }
                        }
                    },
                    enabled = !isLoading
                ) {
                    if (isLoading) {
                        androidx.compose.material3.CircularProgressIndicator(modifier = Modifier.size(16.dp), color = MaterialTheme.colorScheme.onPrimary)
                    } else {
                        Text(if (fpStage == 1) "Next" else if (fpStage == 2) "Verify" else "Reset")
                    }
                }
            },
            dismissButton = {
                TextButton(onClick = { 
                    if (fpStage > 1 && !isLoading && fpStage != 3) {
                        fpStage--
                        fpMessage = ""
                    } else {
                        isForgotPassword = false 
                        fpStage = 1
                    }
                }) {
                    Text(if (fpStage == 2) "Back" else "Cancel")
                }
            }
        )
    }
}

enum class BottomTab { Dashboard, Messages, Profile }

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun HomeScreen(
    viewModel: OrderListViewModel,
    onNavigateToGenerateOrder: () -> Unit,
    onNavigateToOrderDetails: (String) -> Unit,
    onNavigateToChat: (String) -> Unit,
    onLogout: () -> Unit
) {
    var selectedBottomTab by remember { mutableStateOf(BottomTab.Dashboard) }
    var showGlobalSearch by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        when {
                            showGlobalSearch -> "Search Users"
                            selectedBottomTab == BottomTab.Dashboard -> "Dashboard"
                            selectedBottomTab == BottomTab.Messages -> "Messages"
                            selectedBottomTab == BottomTab.Profile -> "My Profile"
                            else -> "Dashboard"
                        },
                        fontWeight = FontWeight.Bold
                    ) 
                },
                actions = {
                    if (selectedBottomTab == BottomTab.Dashboard && !showGlobalSearch) {
                        IconButton(onClick = { showGlobalSearch = true }) {
                            Icon(Icons.Default.Search, contentDescription = "Search Users")
                        }
                        IconButton(onClick = { selectedBottomTab = BottomTab.Profile }) {
                            Icon(Icons.Default.AccountCircle, contentDescription = "Profile")
                        }
                    }
                    if (showGlobalSearch) {
                        IconButton(onClick = { showGlobalSearch = false }) {
                            Text("Clear", fontWeight = FontWeight.Bold)
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.background
                )
            )
        },
        containerColor = MaterialTheme.colorScheme.background,
        bottomBar = {
            NavigationBar(containerColor = MaterialTheme.colorScheme.surface) {
                NavigationBarItem(
                    selected = selectedBottomTab == BottomTab.Dashboard,
                    onClick = { 
                        selectedBottomTab = BottomTab.Dashboard 
                        showGlobalSearch = false
                    },
                    icon = { Icon(Icons.Default.Dashboard, contentDescription = "Dashboard") },
                    label = { Text("Dashboard") }
                )
                NavigationBarItem(
                    selected = selectedBottomTab == BottomTab.Messages,
                    onClick = { 
                        selectedBottomTab = BottomTab.Messages 
                        showGlobalSearch = false
                    },
                    icon = { Icon(Icons.AutoMirrored.Filled.Message, contentDescription = "Messages") },
                    label = { Text("Messages") }
                )
                NavigationBarItem(
                    selected = selectedBottomTab == BottomTab.Profile,
                    onClick = { 
                        selectedBottomTab = BottomTab.Profile 
                        showGlobalSearch = false
                    },
                    icon = { Icon(Icons.Default.AccountCircle, contentDescription = "Profile") },
                    label = { Text("Profile") }
                )
            }
        },
        floatingActionButton = {
            if (selectedBottomTab == BottomTab.Dashboard) {
                FloatingActionButton(
                    onClick = onNavigateToGenerateOrder,
                    shape = MaterialTheme.shapes.medium,
                    containerColor = MaterialTheme.colorScheme.primary,
                    contentColor = MaterialTheme.colorScheme.onPrimary,
                    modifier = Modifier.testTag("fab_generate_order")
                ) {
                    Icon(Icons.Default.Add, contentDescription = "Generate Order")
                }
            }
        }
    ) { padding ->
        if (showGlobalSearch) {
            GlobalSearchContent(
                padding = padding,
                viewModel = viewModel,
                onNavigateToChat = onNavigateToChat
            )
        } else {
            when (selectedBottomTab) {
                BottomTab.Dashboard -> DashboardContent(
                    padding = padding,
                    viewModel = viewModel,
                    onNavigateToOrderDetails = onNavigateToOrderDetails,
                    onNavigateToChat = onNavigateToChat
                )
                BottomTab.Messages -> MessagesContent(
                    padding = padding,
                    viewModel = viewModel,
                    onNavigateToChat = onNavigateToChat
                )
                BottomTab.Profile -> ProfileContent(
                    padding = padding,
                    viewModel = viewModel,
                    onLogout = onLogout
                )
            }
        }
    }
}

@Composable
fun GlobalSearchContent(
    padding: PaddingValues,
    viewModel: OrderListViewModel,
    onNavigateToChat: (String) -> Unit
) {
    var globalQuery by remember { mutableStateOf("") }
    var contactToInvite by remember { mutableStateOf<Pair<String, String>?>(null) }
    val allUsers by viewModel.allUsers.collectAsStateWithLifecycle()
    val currentUser by viewModel.currentUser.collectAsStateWithLifecycle()
    val context = LocalContext.current

    var hasPermission by remember { 
        mutableStateOf(
            ContextCompat.checkSelfPermission(context, Manifest.permission.READ_CONTACTS) == PackageManager.PERMISSION_GRANTED
        )
    }

    val launcher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { isGranted ->
        hasPermission = isGranted
    }

    LaunchedEffect(Unit) {
        if (!hasPermission) {
            launcher.launch(Manifest.permission.READ_CONTACTS)
        }
    }

    var localContacts by remember { mutableStateOf<List<Pair<String, String>>>(emptyList()) }

    LaunchedEffect(hasPermission) {
        if (hasPermission) {
            kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
                val contacts = mutableListOf<Pair<String, String>>()
                try {
                    val cursor = context.contentResolver.query(
                        ContactsContract.CommonDataKinds.Phone.CONTENT_URI,
                        arrayOf(ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME, ContactsContract.CommonDataKinds.Phone.NUMBER),
                        null, null, ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME + " ASC"
                    )
                    cursor?.use {
                        val nameIndex = it.getColumnIndex(ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME)
                        val numberIndex = it.getColumnIndex(ContactsContract.CommonDataKinds.Phone.NUMBER)
                        while (it.moveToNext()) {
                            val name = it.getString(nameIndex) ?: ""
                            val num = it.getString(numberIndex) ?: ""
                            val normalized = num.filter { char -> char.isDigit() }
                            if (normalized.isNotBlank()) {
                                val last10 = if (normalized.length > 10) normalized.takeLast(10) else normalized
                                contacts.add(Pair(name, last10))
                            }
                        }
                    }
                } catch (e: Exception) {
                    android.util.Log.e("Contacts", "Error reading contacts: ${e.message}")
                }
                // Avoid duplicates by number
                localContacts = contacts.distinctBy { it.second }
            }
        }
    }

    val appUsersByPhone = remember(allUsers, currentUser) {
        val map = mutableMapOf<String, com.example.data.User>()
        for (u in allUsers) {
            val userPhone = u.phoneNumber ?: ""
            val normalized = userPhone.filter { char -> char.isDigit() }
            if (normalized.isNotBlank()) {
                val last10 = if (normalized.length > 10) normalized.takeLast(10) else normalized
                map[last10] = u
            }
        }
        map
    }

    val matchedUsers = remember(appUsersByPhone, localContacts) {
        localContacts.mapNotNull { contact ->
            val matchingUser = appUsersByPhone[contact.second]
            if (matchingUser != null) Pair(contact.first, matchingUser) else null
        }
    }

    val unmatchedContacts = remember(appUsersByPhone, localContacts) {
        localContacts.filter { contact ->
            appUsersByPhone[contact.second] == null
        }
    }

    val allAppUsers = remember(allUsers, currentUser, globalQuery) {
        val query = globalQuery.trim()
        val normalizedQuery = query.filter { it.isDigit() }
        
        if (query.isBlank()) {
            allUsers // Show all users by default
        } else {
            allUsers.filter {
                val normalizedPhone = (it.phoneNumber ?: "").filter { char -> char.isDigit() }
                (it.name ?: "").contains(query, ignoreCase = true) ||
                (it.shopName ?: "").contains(query, ignoreCase = true) ||
                (it.email ?: "").contains(query, ignoreCase = true) ||
                (it.phoneNumber ?: "").contains(query) ||
                (normalizedQuery.isNotBlank() && normalizedPhone.contains(normalizedQuery))
            }
        }
    }

    val filteredUnmatchedContacts = remember(localContacts, globalQuery, allUsers) {
        val query = globalQuery.trim()
        val normalizedQuery = query.filter { it.isDigit() }
        val appUserPhones = allUsers.mapNotNull { it.phoneNumber?.filter { c -> c.isDigit() }?.takeLast(10) }.toSet()
        
        val unmatched = localContacts.filter { contact ->
            val contactPhoneStr = contact.second ?: ""
            val contactPhone = contactPhoneStr.filter { c -> c.isDigit() }.takeLast(10)
            !appUserPhones.contains(contactPhone)
        }
        
        if (query.isBlank()) unmatched else unmatched.filter {
            val contactPhone = it.second.filter { c -> c.isDigit() }.takeLast(10)
            it.first.contains(query, ignoreCase = true) || 
            it.second.contains(query, ignoreCase = true) ||
            (normalizedQuery.isNotBlank() && contactPhone.contains(normalizedQuery))
        }
    }

    Column(modifier = Modifier.fillMaxSize().padding(padding)) {
        OutlinedTextField(
            value = globalQuery,
            onValueChange = { globalQuery = it },
            placeholder = { Text("Search your contacts on the app...") },
            leadingIcon = { Icon(Icons.Default.Search, contentDescription = "Search") },
            trailingIcon = {
                if (globalQuery.isNotEmpty()) {
                    IconButton(onClick = { globalQuery = "" }) {
                        Text("X", fontWeight = FontWeight.Bold)
                    }
                }
            },
            modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),
            singleLine = true,
            shape = MaterialTheme.shapes.medium
        )

        if (!hasPermission) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Text("Contacts permission required to find users.", color = MaterialTheme.colorScheme.onSurfaceVariant)
                    Spacer(modifier = Modifier.height(8.dp))
                    Button(onClick = { launcher.launch(Manifest.permission.READ_CONTACTS) }) {
                        Text("Grant Permission")
                    }
                }
            }
        } else {
            LazyColumn(
                modifier = Modifier.weight(1f).padding(horizontal = 16.dp),
                contentPadding = PaddingValues(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                if (allAppUsers.isNotEmpty()) {
                    item {
                        Text("App Users", style = MaterialTheme.typography.titleSmall, color = MaterialTheme.colorScheme.primary, modifier = Modifier.padding(vertical = 4.dp))
                    }
                    items(allAppUsers) { user ->
                        Card(
                            modifier = Modifier.fillMaxWidth().clickable { onNavigateToChat(user.id) },
                            shape = MaterialTheme.shapes.medium,
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
                        ) {
                            Row(
                                modifier = Modifier.padding(16.dp).fillMaxWidth(),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Column(modifier = Modifier.weight(1f)) {
                                    val displayName = (user.name ?: "") + if (user.id == currentUser?.id) " (You)" else ""
                                    Text(displayName, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                                    val safeShopName = user.shopName ?: ""
                                    if (safeShopName.isNotBlank()) {
                                        Text("Shop: $safeShopName", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.secondary)
                                    }
                                    val safePhoneNumber = user.phoneNumber ?: ""
                                    if (safePhoneNumber.isNotBlank()) {
                                        Text(safePhoneNumber, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.tertiary)
                                    }
                                }
                                IconButton(onClick = { onNavigateToChat(user.id ?: "") }) {
                                    Icon(Icons.AutoMirrored.Filled.Message, contentDescription = "Message", tint = MaterialTheme.colorScheme.primary)
                                }
                            }
                        }
                    }
                }

                if (filteredUnmatchedContacts.isNotEmpty()) {
                    item {
                        Text("Invite to App", style = MaterialTheme.typography.titleSmall, color = MaterialTheme.colorScheme.primary, modifier = Modifier.padding(top = 16.dp, bottom = 4.dp))
                    }
                    items(filteredUnmatchedContacts) { (contactName, phoneNumber) ->
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            shape = MaterialTheme.shapes.medium,
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                        ) {
                            Row(
                                modifier = Modifier.padding(16.dp).fillMaxWidth(),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Column(modifier = Modifier.weight(1f)) {
                                    Text(contactName, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                                    Text(phoneNumber, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.secondary)
                                }
                                Button(
                                    onClick = { 
                                        contactToInvite = Pair(contactName, phoneNumber)
                                    },
                                    contentPadding = PaddingValues(horizontal = 12.dp, vertical = 6.dp)
                                ) {
                                    Text("Invite")
                                }
                            }
                        }
                    }
                }
                
                if (localContacts.isEmpty() && globalQuery.isBlank()) {
                    item {
                        Box(modifier = Modifier.fillMaxWidth().padding(32.dp), contentAlignment = Alignment.Center) {
                            Text("No contacts found on your device. Type a name or phone number in the search bar above to search registered app users globally.", color = MaterialTheme.colorScheme.onSurfaceVariant, textAlign = androidx.compose.ui.text.style.TextAlign.Center)
                        }
                    }
                }
            }
        }
        if (contactToInvite != null) {
            val contact = contactToInvite!!
            androidx.compose.material3.AlertDialog(
                onDismissRequest = { contactToInvite = null },
                title = { Text("Invite to App", style = MaterialTheme.typography.titleLarge) },
                text = { Text("How would you like to invite ${contact.first} to join the app?", style = MaterialTheme.typography.bodyMedium) },
                confirmButton = {
                    androidx.compose.material3.TextButton(onClick = {
                        val waUri = android.net.Uri.parse("https://api.whatsapp.com/send?phone=${contact.second}&text=" + android.net.Uri.encode("Hey ${contact.first}! Let's chat and manage orders on the Order List App. Download it now: https://example.com/download"))
                        val waIntent = android.content.Intent(android.content.Intent.ACTION_VIEW, waUri)
                        try {
                            context.startActivity(waIntent)
                        } catch (e: Exception) {
                            android.widget.Toast.makeText(context, "WhatsApp not installed", android.widget.Toast.LENGTH_SHORT).show()
                        }
                        contactToInvite = null
                    }) {
                        Text("WhatsApp", color = MaterialTheme.colorScheme.primary)
                    }
                },
                dismissButton = {
                    androidx.compose.material3.TextButton(onClick = {
                        val inviteUri = android.net.Uri.parse("smsto:${contact.second}")
                        val smsIntent = android.content.Intent(android.content.Intent.ACTION_SENDTO, inviteUri).apply {
                            putExtra("sms_body", "Hey ${contact.first}! Let's chat and manage orders on the Order List App. Download it now: https://example.com/download")
                        }
                        try {
                            context.startActivity(smsIntent)
                        } catch (e: Exception) {
                            android.widget.Toast.makeText(context, "No messaging app found", android.widget.Toast.LENGTH_SHORT).show()
                        }
                        contactToInvite = null
                    }) {
                        Text("SMS", color = MaterialTheme.colorScheme.primary)
                    }
                }
            )
        }
    }
}

@Composable
fun DashboardContent(
    padding: PaddingValues,
    viewModel: OrderListViewModel,
    onNavigateToOrderDetails: (String) -> Unit,
    onNavigateToChat: (String) -> Unit
) {
    var selectedTabIndex by remember { mutableStateOf(0) }
    var searchQuery by remember { mutableStateOf("") }
    val buyerOrders by viewModel.currentBuyerOrders.collectAsStateWithLifecycle()
    val sellerOrders by viewModel.currentSellerOrders.collectAsStateWithLifecycle()

    val sendOrders = remember(buyerOrders, searchQuery) {
        val base = buyerOrders.filter { it.order?.sellerId != "DOWNLOADED" && it.order?.sellerId != "CANCELLED" && it.order?.status != "CANCELLED" }
        if (searchQuery.isBlank()) base else base.filter {
            it.seller?.name.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.seller?.shopName.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.seller?.phoneNumber.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.seller?.email.orEmpty().contains(searchQuery, ignoreCase = true)
        }
    }

    val receiveOrders = remember(sellerOrders, searchQuery) {
        val base = sellerOrders.filter { it.order?.status != "CANCELLED" }
        if (searchQuery.isBlank()) base else base.filter {
            it.buyer?.name.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.buyer?.shopName.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.buyer?.phoneNumber.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.buyer?.email.orEmpty().contains(searchQuery, ignoreCase = true)
        }
    }

    val downloadedOrders = remember(buyerOrders, searchQuery) {
        val base = buyerOrders.filter { it.order?.sellerId == "DOWNLOADED" }
        if (searchQuery.isBlank()) base else base.filter {
            it.items?.any { item -> item.name.contains(searchQuery, ignoreCase = true) } ?: false
        }
    }

    val cancelledOrders = remember(buyerOrders, sellerOrders, searchQuery) {
        val baseBuy = buyerOrders.filter { it.order?.sellerId == "CANCELLED" || it.order?.status == "CANCELLED" }
        val baseSell = sellerOrders.filter { it.order?.status == "CANCELLED" }
        val base = (baseBuy + baseSell).distinctBy { it.order?.id }
        if (searchQuery.isBlank()) base else base.filter {
            it.items?.any { item -> item.name.contains(searchQuery, ignoreCase = true) } ?: false ||
            it.seller?.name.orEmpty().contains(searchQuery, ignoreCase = true) ||
            it.buyer?.name.orEmpty().contains(searchQuery, ignoreCase = true)
        }
    }

    Column(modifier = Modifier.fillMaxSize().padding(padding)) {
        ScrollableTabRow(
            selectedTabIndex = selectedTabIndex,
            containerColor = MaterialTheme.colorScheme.background,
            edgePadding = 16.dp
        ) {
            Tab(
                selected = selectedTabIndex == 0,
                onClick = { selectedTabIndex = 0 },
                text = { Text("Send") }
            )
            Tab(
                selected = selectedTabIndex == 1,
                onClick = { selectedTabIndex = 1 },
                text = { Text("Receive") }
            )
            Tab(
                selected = selectedTabIndex == 2,
                onClick = { selectedTabIndex = 2 },
                text = { Text("Download") }
            )
            Tab(
                selected = selectedTabIndex == 3,
                onClick = { selectedTabIndex = 3 },
                text = { Text("Cancel") }
            )
        }
        
        OutlinedTextField(
            value = searchQuery,
            onValueChange = { searchQuery = it },
            placeholder = { Text("Search by name, shop, or phone...") },
            leadingIcon = { Icon(Icons.Default.Search, contentDescription = "Search") },
            trailingIcon = {
                if (searchQuery.isNotEmpty()) {
                    IconButton(onClick = { searchQuery = "" }) {
                        Text("X", fontWeight = FontWeight.Bold)
                    }
                }
            },
            modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),
            singleLine = true,
            shape = MaterialTheme.shapes.medium
        )

        LazyColumn(
            modifier = Modifier.weight(1f).padding(horizontal = 16.dp),
            contentPadding = PaddingValues(vertical = 8.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            when (selectedTabIndex) {
                0 -> {
                    items(sendOrders) { orderWithDetails ->
                        val name = orderWithDetails.seller?.name
                        val displayPartyName = if (orderWithDetails.order?.sellerId == "EXTERNAL") "External Shared Document" else if (name.isNullOrBlank()) "Unknown Contact" else name
                        OrderCard(
                            orderWithDetails = orderWithDetails,
                            otherPartyName = displayPartyName,
                            onClick = { onNavigateToOrderDetails(orderWithDetails.order?.id ?: "") },
                            onMessageClick = { onNavigateToChat(orderWithDetails.seller?.id ?: "") },
                            showChatButton = orderWithDetails.order?.sellerId != "EXTERNAL"
                        )
                    }
                }
                1 -> {
                    items(receiveOrders) { orderWithDetails ->
                        val name = orderWithDetails.buyer?.name
                        val displayPartyName = if (name.isNullOrBlank()) "Unknown Contact" else name
                        OrderCard(
                            orderWithDetails = orderWithDetails,
                            otherPartyName = displayPartyName,
                            onClick = { onNavigateToOrderDetails(orderWithDetails.order?.id ?: "") },
                            onMessageClick = { onNavigateToChat(orderWithDetails.buyer?.id ?: "") },
                            showChatButton = true
                        )
                    }
                }
                2 -> {
                    items(downloadedOrders) { orderWithDetails ->
                        OrderCard(
                            orderWithDetails = orderWithDetails,
                            otherPartyName = "Downloaded Document",
                            onClick = { onNavigateToOrderDetails(orderWithDetails.order?.id ?: "") },
                            onMessageClick = {},
                            showChatButton = false
                        )
                    }
                }
                3 -> {
                    items(cancelledOrders) { orderWithDetails ->
                        val isSeller = orderWithDetails.order?.sellerId == (viewModel.currentUser.value?.id ?: "")
                        val otherPartyName = if (orderWithDetails.order?.sellerId == "CANCELLED") {
                            "Cancelled Document"
                        } else if (isSeller) {
                            orderWithDetails.buyer?.name.takeIf { !it.isNullOrBlank() } ?: "Unknown Contact"
                        } else {
                            orderWithDetails.seller?.name.takeIf { !it.isNullOrBlank() } ?: "Unknown Contact"
                        }
                        OrderCard(
                            orderWithDetails = orderWithDetails,
                            otherPartyName = otherPartyName,
                            onClick = { onNavigateToOrderDetails(orderWithDetails.order?.id ?: "") },
                            onMessageClick = {},
                            showChatButton = false
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun OrderCard(
    orderWithDetails: OrderWithDetails,
    otherPartyName: String,
    onClick: () -> Unit,
    onMessageClick: () -> Unit,
    showChatButton: Boolean = true
) {
    Card(
        modifier = Modifier.fillMaxWidth().clickable { onClick() },
        shape = MaterialTheme.shapes.large,
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        elevation = CardDefaults.cardElevation(defaultElevation = 1.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                Text(otherPartyName, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                StatusBadge(orderWithDetails.order?.status ?: "")
            }
            Spacer(modifier = Modifier.height(8.dp))
            Text("${orderWithDetails.items?.size ?: 0} items", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.secondary)
            
            if (showChatButton) {
                Spacer(modifier = Modifier.height(12.dp))
                Button(
                    onClick = onMessageClick,
                    shape = MaterialTheme.shapes.medium,
                    modifier = Modifier.fillMaxWidth().height(40.dp)
                ) {
                    Text("Message")
                }
            }
        }
    }
}

@Composable
fun StatusBadge(status: String) {
    val (bgColor, textColor) = when (status) {
        "DONE" -> MaterialTheme.colorScheme.tertiaryContainer to MaterialTheme.colorScheme.onTertiaryContainer
        "CANCELLED" -> MaterialTheme.colorScheme.errorContainer to MaterialTheme.colorScheme.onErrorContainer
        else -> MaterialTheme.colorScheme.primaryContainer to MaterialTheme.colorScheme.onPrimaryContainer
    }
    
    Box(
        modifier = Modifier
            .background(bgColor, RoundedCornerShape(12.dp))
            .padding(horizontal = 12.dp, vertical = 4.dp)
    ) {
        Text(
            text = status,
            color = textColor,
            style = MaterialTheme.typography.labelSmall,
            fontWeight = FontWeight.Bold
        )
    }
}

@Composable
fun ProfileContent(
    padding: PaddingValues,
    viewModel: OrderListViewModel,
    onLogout: () -> Unit
) {
    val currentUser by viewModel.currentUser.collectAsStateWithLifecycle()
    val context = androidx.compose.ui.platform.LocalContext.current
    
    var showNameDialog by androidx.compose.runtime.remember { androidx.compose.runtime.mutableStateOf(false) }
    var editName by androidx.compose.runtime.remember { androidx.compose.runtime.mutableStateOf("") }
    var showShopDialog by androidx.compose.runtime.remember { androidx.compose.runtime.mutableStateOf(false) }
    var editShopName by androidx.compose.runtime.remember { androidx.compose.runtime.mutableStateOf("") }

    val launcher = androidx.activity.compose.rememberLauncherForActivityResult(
        contract = androidx.activity.result.contract.ActivityResultContracts.PickVisualMedia()
    ) { uri: android.net.Uri? ->
        uri?.let {
            try {
                val inputStream = context.contentResolver.openInputStream(it)
                val bytes = inputStream?.readBytes()
                inputStream?.close()
                if (bytes != null) {
                    val bitmap = android.graphics.BitmapFactory.decodeByteArray(bytes, 0, bytes.size)
                    val scaledBitmap = android.graphics.Bitmap.createScaledBitmap(
                        bitmap, 300, (300.0 * bitmap.height / bitmap.width).toInt(), true
                    )
                    val outputStream = java.io.ByteArrayOutputStream()
                    scaledBitmap.compress(android.graphics.Bitmap.CompressFormat.JPEG, 70, outputStream)
                    val compressedBytes = outputStream.toByteArray()
                    val base64 = android.util.Base64.encodeToString(compressedBytes, android.util.Base64.DEFAULT)
                    viewModel.updateUserProfile(currentUser?.name ?: "", currentUser?.shopName ?: "", base64) { success, msg ->
                        if (!success) android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                    }
                }
            } catch (e: Exception) {
                android.widget.Toast.makeText(context, "Error loading image", android.widget.Toast.LENGTH_SHORT).show()
            }
        }
    }

    if (showNameDialog) {
        androidx.compose.material3.AlertDialog(
            onDismissRequest = { showNameDialog = false },
            title = { Text("Enter your name") },
            text = {
                androidx.compose.material3.OutlinedTextField(
                    value = editName,
                    onValueChange = { editName = it },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            },
            confirmButton = {
                androidx.compose.material3.TextButton(onClick = {
                    showNameDialog = false
                    viewModel.updateUserProfile(editName, currentUser?.shopName ?: "", currentUser?.profileImage) { success, msg ->
                        if (!success) android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                    }
                }) { Text("Save") }
            },
            dismissButton = {
                androidx.compose.material3.TextButton(onClick = { showNameDialog = false }) { Text("Cancel") }
            }
        )
    }

    if (showShopDialog) {
        androidx.compose.material3.AlertDialog(
            onDismissRequest = { showShopDialog = false },
            title = { Text("Enter your shop name") },
            text = {
                androidx.compose.material3.OutlinedTextField(
                    value = editShopName,
                    onValueChange = { editShopName = it },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            },
            confirmButton = {
                androidx.compose.material3.TextButton(onClick = {
                    showShopDialog = false
                    viewModel.updateUserProfile(currentUser?.name ?: "", editShopName, currentUser?.profileImage) { success, msg ->
                        if (!success) android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                    }
                }) { Text("Save") }
            },
            dismissButton = {
                androidx.compose.material3.TextButton(onClick = { showShopDialog = false }) { Text("Cancel") }
            }
        )
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(padding)
            .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f))
    ) {
        val imageBitmap = androidx.compose.runtime.remember(currentUser?.profileImage) {
            val base64String = currentUser?.profileImage
            if (!base64String.isNullOrBlank()) {
                try {
                    val decodedString = android.util.Base64.decode(base64String, android.util.Base64.DEFAULT)
                    android.graphics.BitmapFactory.decodeByteArray(decodedString, 0, decodedString.size)?.asImageBitmap()
                } catch (e: Exception) { null }
            } else null
        }

        Box(modifier = Modifier.fillMaxWidth().padding(vertical = 32.dp), contentAlignment = Alignment.Center) {
            Box(modifier = Modifier.size(140.dp)) {
                if (imageBitmap != null) {
                    Image(
                        bitmap = imageBitmap,
                        contentDescription = "Profile Avatar",
                        modifier = Modifier
                            .fillMaxSize()
                            .clip(androidx.compose.foundation.shape.CircleShape)
                            .background(MaterialTheme.colorScheme.surface),
                        contentScale = androidx.compose.ui.layout.ContentScale.Crop
                    )
                } else {
                    Icon(
                        imageVector = Icons.Default.AccountCircle,
                        contentDescription = "Profile Avatar",
                        modifier = Modifier.fillMaxSize().clip(androidx.compose.foundation.shape.CircleShape).background(MaterialTheme.colorScheme.surface),
                        tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f)
                    )
                }
                Box(
                    modifier = Modifier
                        .align(Alignment.BottomEnd)
                        .offset(x = (-8).dp, y = (-8).dp)
                        .background(MaterialTheme.colorScheme.primary, androidx.compose.foundation.shape.CircleShape)
                        .clickable {
                            launcher.launch(androidx.activity.result.PickVisualMediaRequest(androidx.activity.result.contract.ActivityResultContracts.PickVisualMedia.ImageOnly))
                        }
                        .padding(10.dp)
                ) {
                    Icon(Icons.Default.Edit, contentDescription = "Change photo", tint = MaterialTheme.colorScheme.onPrimary, modifier = Modifier.size(20.dp))
                }
            }
        }
        
        ProfileItemRow(
            icon = Icons.Default.AccountCircle,
            label = "Name",
            value = currentUser?.name ?: "Unknown",
            subValue = "This is not your username or pin. This name will be visible to your contacts.",
            onClick = {
                editName = currentUser?.name ?: ""
                showNameDialog = true
            }
        )
        
        androidx.compose.material3.HorizontalDivider(modifier = Modifier.padding(start = 72.dp))
        
        ProfileItemRow(
            icon = Icons.Default.Dashboard,
            label = "Shop Name",
            value = currentUser?.shopName.takeIf { !it.isNullOrBlank() } ?: "Not set",
            onClick = {
                editShopName = currentUser?.shopName ?: ""
                showShopDialog = true
            }
        )
        
        androidx.compose.material3.HorizontalDivider(modifier = Modifier.padding(start = 72.dp))
        
        ProfileItemRow(
            icon = Icons.Default.CheckCircle,
            label = "Phone",
            value = currentUser?.phoneNumber.takeIf { !it.isNullOrBlank() } ?: "Not set",
            onClick = null
        )

        Spacer(modifier = Modifier.weight(1f))
        
        OutlinedButton(
            onClick = onLogout,
            modifier = Modifier.fillMaxWidth().padding(16.dp).height(48.dp),
            shape = MaterialTheme.shapes.medium
        ) {
            Icon(Icons.AutoMirrored.Filled.Logout, contentDescription = null)
            Spacer(modifier = Modifier.width(8.dp))
            Text("Logout")
        }
    }
}

@Composable
fun ProfileItemRow(
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    label: String,
    value: String,
    subValue: String? = null,
    onClick: (() -> Unit)? = null
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(enabled = onClick != null) { onClick?.invoke() }
            .padding(vertical = 16.dp, horizontal = 24.dp),
        verticalAlignment = Alignment.Top
    ) {
        Icon(
            imageVector = icon,
            contentDescription = null,
            tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.6f),
            modifier = Modifier.padding(top = 4.dp).size(24.dp)
        )
        Spacer(modifier = Modifier.width(24.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(label, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.8f))
            Text(value, style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurface)
            if (subValue != null) {
                Spacer(modifier = Modifier.height(4.dp))
                Text(subValue, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.8f))
            }
        }
        if (onClick != null) {
            Icon(
                imageVector = Icons.Default.Edit,
                contentDescription = "Edit",
                tint = MaterialTheme.colorScheme.primary,
                modifier = Modifier.padding(top = 8.dp).size(20.dp)
            )
        }
    }
}
